stages:
  - test

test ui:
  stage: test
  image: python:3.9
  before_script:
    - apt-get update
    - apt-get install -y wget gnupg2
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - dpkg -i google-chrome-stable_current_amd64.deb || apt-get -f install -y
    - apt-get install -y libxss1 libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libcups2 libgdk-pixbuf2.0-0 libnspr4 libnss3 libx11-xcb1 libxtst6 libxrandr2 xdg-utils libgbm1
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - python -m unittest shop_sample_test